//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoNeed01
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBDATA
    {
        public int ID { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public string MNAME { get; set; }
        public string DES_MOBILE { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string IMG { get; set; }
    }
}
